openapi: 3.0.0
info:
  title: Pizza API
  version: 1.0.0

paths:
  /menu:
    get:
      summary: Get pizza menu
      responses:
        '200':
          description: Menu list

  /order:
    post:
      summary: Place pizza order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                pizza:
                  type: string
                size:
                  type: string
                quantity:
                  type: integer
      responses:
        '200':
          description: Order created

  /order/{order_id}:
    get:
      summary: Track order
      parameters:
        - name: order_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Order status

  /schedule:
    post:
      summary: Schedule delivery
      operationId: scheduleDelivery
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                order_id:
                  type: string
                time:
                  type: string
      responses:
        "200":
          description: Delivery scheduled